package online.cheesysocks.cspawners.utils;


import org.bukkit.Bukkit;
import org.bukkit.entity.EntityType;
import org.mineacademy.remain.model.CompMaterial;

//import org.bukkit.plugin.Plugin;

import online.cheesysocks.cspawners.spawnerRecipe.SpawnerRC;

public class RegisterSP {
	
	static boolean point9 = Bukkit.getVersion().contains("1.9") || Bukkit.getVersion().contains("1.10") || Bukkit.getVersion().contains("1.11") || Bukkit.getVersion().contains("1.12") || Bukkit.getVersion().contains("1.13")|| Bukkit.getVersion().contains("1.14");
	static boolean point10 = Bukkit.getVersion().contains("1.10") || Bukkit.getVersion().contains("1.11") || Bukkit.getVersion().contains("1.12") || Bukkit.getVersion().contains("1.13")|| Bukkit.getVersion().contains("1.14");
	static boolean point11 = Bukkit.getVersion().contains("1.11") || Bukkit.getVersion().contains("1.12") || Bukkit.getVersion().contains("1.13")|| Bukkit.getVersion().contains("1.14");
	static boolean point12 = Bukkit.getVersion().contains("1.12") || Bukkit.getVersion().contains("1.13")|| Bukkit.getVersion().contains("1.14");
	static boolean point13 = Bukkit.getVersion().contains("1.13")|| Bukkit.getVersion().contains("1.14");
	static boolean point14 = Bukkit.getVersion().contains("1.14");
	
	public static void registerRecipes() {
		if(enableRCP.recipeEnabled("Cow"))SpawnerRC.MobRecipes("cowKey", EntityType.COW, "Cow", CompMaterial.LEATHER.getMaterial(), CompMaterial.BEEF.getMaterial(), CompMaterial.LEATHER.getMaterial(), CompMaterial.LEATHER.getMaterial(), CompMaterial.BEEF.getMaterial());
		if(enableRCP.recipeEnabled("Pig"))SpawnerRC.MobRecipes("pigKey", EntityType.PIG, "Pig", CompMaterial.PORKCHOP.getMaterial(), CompMaterial.PORKCHOP.getMaterial(), CompMaterial.PORKCHOP.getMaterial(), CompMaterial.PORKCHOP.getMaterial(), CompMaterial.PORKCHOP.getMaterial());
		if(enableRCP.recipeEnabled("Sheep"))SpawnerRC.MobRecipes("sheepKey", EntityType.SHEEP, "Sheep", CompMaterial.MUTTON.getMaterial(), CompMaterial.WHITE_WOOL.getMaterial(), CompMaterial.MUTTON.getMaterial(), CompMaterial.WHITE_WOOL.getMaterial(), CompMaterial.MUTTON.getMaterial());
		if(enableRCP.recipeEnabled("Chicken"))SpawnerRC.MobRecipes("chickenKey", EntityType.CHICKEN, "Chicken", CompMaterial.CHICKEN.getMaterial(), CompMaterial.FEATHER.getMaterial(), CompMaterial.CHICKEN.getMaterial(), CompMaterial.CHICKEN.getMaterial(), CompMaterial.FEATHER.getMaterial());
		if(enableRCP.recipeEnabled("Mooshroom"))SpawnerRC.MobRecipes("mooshroomKey", EntityType.MUSHROOM_COW, "Mooshroom", CompMaterial.BROWN_MUSHROOM.getMaterial(), CompMaterial.BEEF.getMaterial(), CompMaterial.RED_MUSHROOM.getMaterial(), CompMaterial.BROWN_MUSHROOM.getMaterial(), CompMaterial.RED_MUSHROOM.getMaterial());
		if(enableRCP.recipeEnabled("Dolphin") && point14)SpawnerRC.MobRecipes("dolphinKey", EntityType.DOLPHIN, "Dolphin", CompMaterial.SALMON.getMaterial(), CompMaterial.COD.getMaterial(), CompMaterial.SALMON.getMaterial(), CompMaterial.COD.getMaterial(), CompMaterial.SALMON.getMaterial());
		if(enableRCP.recipeEnabled("Rabbit"))SpawnerRC.MobRecipes("rabbitKey", EntityType.RABBIT, "Rabbit", CompMaterial.RABBIT.getMaterial(), CompMaterial.RABBIT_HIDE.getMaterial(), CompMaterial.RABBIT.getMaterial(), CompMaterial.RABBIT.getMaterial(), CompMaterial.RABBIT_HIDE.getMaterial());
		if(enableRCP.recipeEnabled("Squid"))SpawnerRC.MobRecipes("squidKey", EntityType.SQUID, "Squid", CompMaterial.INK_SAC.getMaterial(), CompMaterial.INK_SAC.getMaterial(), CompMaterial.INK_SAC.getMaterial(), CompMaterial.INK_SAC.getMaterial(), CompMaterial.INK_SAC.getMaterial());
		if(enableRCP.recipeEnabled("Donkey"))SpawnerRC.MobRecipes("donkeyKey", EntityType.DONKEY, "Donkey", CompMaterial.LEATHER.getMaterial(), CompMaterial.CHEST.getMaterial(), CompMaterial.SADDLE.getMaterial(), CompMaterial.CHEST.getMaterial(), CompMaterial.SADDLE.getMaterial());
		if(enableRCP.recipeEnabled("Horse"))SpawnerRC.MobRecipes("horseKey", EntityType.HORSE, "Horse", CompMaterial.LEATHER.getMaterial(), CompMaterial.IRON_HORSE_ARMOR.getMaterial(), CompMaterial.SADDLE.getMaterial(), CompMaterial.IRON_HORSE_ARMOR.getMaterial(), CompMaterial.SADDLE.getMaterial());
		if(enableRCP.recipeEnabled("Ocelot"))SpawnerRC.MobRecipes("ocelotKey", EntityType.OCELOT, "Ocelot", CompMaterial.TROPICAL_FISH.getMaterial(), CompMaterial.COD.getMaterial(), CompMaterial.SALMON.getMaterial(), CompMaterial.SALMON.getMaterial(), CompMaterial.TROPICAL_FISH.getMaterial());
		if(enableRCP.recipeEnabled("Wolf"))SpawnerRC.MobRecipes("wolfKey", EntityType.WOLF, "Wolf", CompMaterial.BONE.getMaterial(), CompMaterial.BONE.getMaterial(), CompMaterial.BONE.getMaterial(), CompMaterial.BONE.getMaterial(), CompMaterial.BONE.getMaterial());
		if(enableRCP.recipeEnabled("Villager"))SpawnerRC.MobRecipes("villagerKey", EntityType.VILLAGER, "Villager", CompMaterial.EMERALD.getMaterial(), CompMaterial.EMERALD.getMaterial(), CompMaterial.EMERALD.getMaterial(), CompMaterial.EMERALD.getMaterial(), CompMaterial.EMERALD.getMaterial());
		if(enableRCP.recipeEnabled("Cave Spider"))SpawnerRC.MobRecipes("caveSpiderKey", EntityType.CAVE_SPIDER, "Cave Spider", CompMaterial.COBWEB.getMaterial(), CompMaterial.STRING.getMaterial(), CompMaterial.COBWEB.getMaterial(), CompMaterial.STRING.getMaterial(), CompMaterial.COBWEB.getMaterial());
		if(enableRCP.recipeEnabled("Enderman"))SpawnerRC.MobRecipes("endermanKey", EntityType.ENDERMAN, "Enderman", CompMaterial.ENDER_PEARL.getMaterial(), CompMaterial.ENDER_PEARL.getMaterial(), CompMaterial.ENDER_EYE.getMaterial(), CompMaterial.ENDER_EYE.getMaterial(), CompMaterial.ENDER_PEARL.getMaterial());
		if(enableRCP.recipeEnabled("Spider"))SpawnerRC.MobRecipes("spiderKey", EntityType.SPIDER, "Spider", CompMaterial.SPIDER_EYE.getMaterial(), CompMaterial.STRING.getMaterial(), CompMaterial.SPIDER_EYE.getMaterial(), CompMaterial.SPIDER_EYE.getMaterial(), CompMaterial.STRING.getMaterial());
		if(enableRCP.recipeEnabled("Zombie"))SpawnerRC.MobRecipes("zombieKey", EntityType.ZOMBIE, "Zombie", CompMaterial.ROTTEN_FLESH.getMaterial(), CompMaterial.ROTTEN_FLESH.getMaterial(), CompMaterial.ROTTEN_FLESH.getMaterial(), CompMaterial.ROTTEN_FLESH.getMaterial(), CompMaterial.ROTTEN_FLESH.getMaterial());
		if(enableRCP.recipeEnabled("Zombie Pigman"))SpawnerRC.MobRecipes("zombiePigmanKey", EntityType.PIG_ZOMBIE, "Zombie Pigman", CompMaterial.ROTTEN_FLESH.getMaterial(), CompMaterial.PORKCHOP.getMaterial(), CompMaterial.ROTTEN_FLESH.getMaterial(), CompMaterial.PORKCHOP.getMaterial(), CompMaterial.ROTTEN_FLESH.getMaterial());
		if(enableRCP.recipeEnabled("Zombie Villager"))SpawnerRC.MobRecipes("zombieVillagerKey", EntityType.ZOMBIE_VILLAGER, "Zombie Villager", CompMaterial.EMERALD.getMaterial(), CompMaterial.ROTTEN_FLESH.getMaterial(), CompMaterial.EMERALD.getMaterial(), CompMaterial.EMERALD.getMaterial(), CompMaterial.ROTTEN_FLESH.getMaterial());
		if(enableRCP.recipeEnabled("Blaze"))SpawnerRC.MobRecipes("blazeKey", EntityType.BLAZE, "Blaze", CompMaterial.BLAZE_ROD.getMaterial(), CompMaterial.BLAZE_POWDER.getMaterial(), CompMaterial.BLAZE_ROD.getMaterial(), CompMaterial.BLAZE_ROD.getMaterial(), CompMaterial.BLAZE_POWDER.getMaterial());
		if(enableRCP.recipeEnabled("Creeper"))SpawnerRC.MobRecipes("creeperKey", EntityType.CREEPER, "Creeper", CompMaterial.GUNPOWDER.getMaterial(), CompMaterial.TNT.getMaterial(), CompMaterial.GUNPOWDER.getMaterial(), CompMaterial.GUNPOWDER.getMaterial(), CompMaterial.TNT.getMaterial());
		if(enableRCP.recipeEnabled("Elder Guardian"))SpawnerRC.MobRecipes("elderGuardianKey", EntityType.ELDER_GUARDIAN, "Elder Guardian", CompMaterial.PRISMARINE_CRYSTALS.getMaterial(), CompMaterial.SPONGE.getMaterial(), CompMaterial.PRISMARINE_SHARD.getMaterial(), CompMaterial.PRISMARINE_CRYSTALS.getMaterial(), CompMaterial.SPONGE.getMaterial());
		if(enableRCP.recipeEnabled("Guardian"))SpawnerRC.MobRecipes("guardianKey", EntityType.GUARDIAN, "Guardian", CompMaterial.PRISMARINE_CRYSTALS.getMaterial(), CompMaterial.PRISMARINE_SHARD.getMaterial(), CompMaterial.PRISMARINE_CRYSTALS.getMaterial(), CompMaterial.PRISMARINE_CRYSTALS.getMaterial(), CompMaterial.PRISMARINE_SHARD.getMaterial());
		if(enableRCP.recipeEnabled("Ghast"))SpawnerRC.MobRecipes("ghastKey", EntityType.GHAST, "Ghast", CompMaterial.FIRE_CHARGE.getMaterial(), CompMaterial.GHAST_TEAR.getMaterial(), CompMaterial.GUNPOWDER.getMaterial(), CompMaterial.GHAST_TEAR.getMaterial(), CompMaterial.FIRE_CHARGE.getMaterial());
		if(enableRCP.recipeEnabled("Magma Cube"))SpawnerRC.MobRecipes("magmaCubeKey", EntityType.MAGMA_CUBE, "Magma Cube", CompMaterial.MAGMA_CREAM.getMaterial(), CompMaterial.MAGMA_CREAM.getMaterial(), CompMaterial.MAGMA_CREAM.getMaterial(), CompMaterial.MAGMA_CREAM.getMaterial(), CompMaterial.MAGMA_CREAM.getMaterial());
		if(enableRCP.recipeEnabled("Silverfish"))SpawnerRC.MobRecipes("silverfishKey", EntityType.SILVERFISH, "Silverfish", CompMaterial.STONE.getMaterial(), CompMaterial.IRON_INGOT.getMaterial(), CompMaterial.STONE.getMaterial(), CompMaterial.STONE.getMaterial(), CompMaterial.IRON_INGOT.getMaterial());
		if(enableRCP.recipeEnabled("Skeleton"))SpawnerRC.MobRecipes("skeletonKey", EntityType.SKELETON, "Skeleton", CompMaterial.BONE.getMaterial(), CompMaterial.ARROW.getMaterial(), CompMaterial.BONE.getMaterial(), CompMaterial.BONE.getMaterial(), CompMaterial.ARROW.getMaterial());
		if(enableRCP.recipeEnabled("Slime"))SpawnerRC.MobRecipes("slimeKey", EntityType.SLIME, "Slime", CompMaterial.SLIME_BLOCK.getMaterial(), CompMaterial.SLIME_BALL.getMaterial(), CompMaterial.SLIME_BLOCK.getMaterial(), CompMaterial.SLIME_BLOCK.getMaterial(), CompMaterial.SLIME_BALL.getMaterial());
		if(enableRCP.recipeEnabled("Witch"))SpawnerRC.MobRecipes("witchKey", EntityType.WITCH, "Witch", CompMaterial.GLASS_BOTTLE.getMaterial(), CompMaterial.GLOWSTONE_DUST.getMaterial(), CompMaterial.SUGAR.getMaterial(), CompMaterial.GLASS_BOTTLE.getMaterial(), CompMaterial.GLOWSTONE_DUST.getMaterial());
		if(enableRCP.recipeEnabled("Wither Skeleton"))SpawnerRC.MobRecipes("witherSkeletonKey", EntityType.WITHER_SKELETON, "Wither Skeleton", CompMaterial.WITHER_SKELETON_SKULL.getMaterial(), CompMaterial.BONE.getMaterial(), CompMaterial.WITHER_SKELETON_SKULL.getMaterial(), CompMaterial.BONE.getMaterial(), CompMaterial.WITHER_SKELETON_SKULL.getMaterial());
		if(enableRCP.recipeEnabled("Shulker") && point9)SpawnerRC.MobRecipes("shulkerKey", EntityType.SHULKER, "Shulker", CompMaterial.SHULKER_SHELL.getMaterial(), CompMaterial.SHULKER_SHELL.getMaterial(), CompMaterial.SHULKER_SHELL.getMaterial(), CompMaterial.SHULKER_SHELL.getMaterial(), CompMaterial.SHULKER_SHELL.getMaterial());
		if(enableRCP.recipeEnabled("Polar Bear") && point10)SpawnerRC.MobRecipes("polarBearKey", EntityType.POLAR_BEAR, "Polar Bear", CompMaterial.SNOW_BLOCK.getMaterial(), CompMaterial.SALMON.getMaterial(), CompMaterial.COD.getMaterial(), CompMaterial.SNOW_BLOCK.getMaterial(), CompMaterial.SALMON.getMaterial());
		if(enableRCP.recipeEnabled("Husk") && point10)SpawnerRC.MobRecipes("huskKey", EntityType.HUSK, "Husk", CompMaterial.CARROT.getMaterial(), CompMaterial.ROTTEN_FLESH.getMaterial(), CompMaterial.POTATO.getMaterial(), CompMaterial.ROTTEN_FLESH.getMaterial(), CompMaterial.IRON_INGOT.getMaterial());
		if(enableRCP.recipeEnabled("Stray") && point10)SpawnerRC.MobRecipes("strayKey", EntityType.STRAY, "Stray", CompMaterial.BONE.getMaterial(), CompMaterial.BOW.getMaterial(), CompMaterial.ARROW.getMaterial(), CompMaterial.BOW.getMaterial(), CompMaterial.BONE.getMaterial());
		if(enableRCP.recipeEnabled("Llama") && point11)SpawnerRC.MobRecipes("llamaKey", EntityType.LLAMA, "Llama", CompMaterial.RED_CARPET.getMaterial(), CompMaterial.LEATHER.getMaterial(), CompMaterial.CHEST.getMaterial(), CompMaterial.CHEST.getMaterial(), CompMaterial.RED_CARPET.getMaterial());
		if(enableRCP.recipeEnabled("Evoker") && point11)SpawnerRC.MobRecipes("evokerKey", EntityType.EVOKER, "Evoker", CompMaterial.EMERALD.getMaterial(), CompMaterial.TOTEM_OF_UNDYING.getMaterial(), CompMaterial.EMERALD.getMaterial(), CompMaterial.EMERALD.getMaterial(), CompMaterial.TOTEM_OF_UNDYING.getMaterial());
		if(enableRCP.recipeEnabled("Vex") && point11)SpawnerRC.MobRecipes("vexKey", EntityType.VEX, "Vex", CompMaterial.IRON_SWORD.getMaterial(), CompMaterial.EMERALD.getMaterial(), CompMaterial.IRON_SWORD.getMaterial(), CompMaterial.EMERALD.getMaterial(), CompMaterial.IRON_SWORD.getMaterial());
		if(enableRCP.recipeEnabled("Vindicator") && point11)SpawnerRC.MobRecipes("vindicatorKey", EntityType.VINDICATOR, "Vindicator", CompMaterial.EMERALD.getMaterial(), CompMaterial.IRON_AXE.getMaterial(), CompMaterial.EMERALD.getMaterial(), CompMaterial.EMERALD.getMaterial(), CompMaterial.IRON_AXE.getMaterial());
		if(enableRCP.recipeEnabled("Parrot") && point12)SpawnerRC.MobRecipes("parrotKey", EntityType.PARROT, "Parrot", CompMaterial.FEATHER.getMaterial(), CompMaterial.FEATHER.getMaterial(), CompMaterial.FEATHER.getMaterial(), CompMaterial.FEATHER.getMaterial(), CompMaterial.FEATHER.getMaterial());
		if(enableRCP.recipeEnabled("Illusioner") && point12)SpawnerRC.MobRecipes("illusionerKey", EntityType.ILLUSIONER, "Illusioner", CompMaterial.BOW.getMaterial(), CompMaterial.BOW.getMaterial(), CompMaterial.BOW.getMaterial(), CompMaterial.BOW.getMaterial(), CompMaterial.BOW.getMaterial());
		if(enableRCP.recipeEnabled("COD.getMaterial()") && point13)SpawnerRC.MobRecipes("COD.getMaterial()Key", EntityType.COD, "COD.getMaterial()", CompMaterial.COD.getMaterial(), CompMaterial.COD.getMaterial(), CompMaterial.COOKED_COD.getMaterial(), CompMaterial.COD.getMaterial(), CompMaterial.COOKED_COD.getMaterial());
		if(enableRCP.recipeEnabled("SALMON.getMaterial()") && point13)SpawnerRC.MobRecipes("SALMON.getMaterial()Key", EntityType.SALMON, "SALMON.getMaterial()", CompMaterial.SALMON.getMaterial(), CompMaterial.COOKED_SALMON.getMaterial(), CompMaterial.SALMON.getMaterial(), CompMaterial.SALMON.getMaterial(), CompMaterial.COOKED_SALMON.getMaterial());
		if(enableRCP.recipeEnabled("Turtle") && point13)SpawnerRC.MobRecipes("turtleKey", EntityType.TURTLE, "Turtle", CompMaterial.SEAGRASS.getMaterial(), CompMaterial.TURTLE_EGG.getMaterial(), CompMaterial.SEAGRASS.getMaterial(), CompMaterial.SEAGRASS.getMaterial(), CompMaterial.TURTLE_EGG.getMaterial());
		if(enableRCP.recipeEnabled("Drowned") && point13)SpawnerRC.MobRecipes("drownedKey", EntityType.DROWNED, "Drowned", CompMaterial.ROTTEN_FLESH.getMaterial(), CompMaterial.TRIDENT.getMaterial(), CompMaterial.ROTTEN_FLESH.getMaterial(), CompMaterial.TRIDENT.getMaterial(), CompMaterial.ROTTEN_FLESH.getMaterial());
		if(enableRCP.recipeEnabled("Phantom") && point13)SpawnerRC.MobRecipes("phantomKey", EntityType.PHANTOM, "Phantom", CompMaterial.PHANTOM_MEMBRANE.getMaterial(), CompMaterial.PHANTOM_MEMBRANE.getMaterial(), CompMaterial.PHANTOM_MEMBRANE.getMaterial(), CompMaterial.PHANTOM_MEMBRANE.getMaterial(), CompMaterial.PHANTOM_MEMBRANE.getMaterial());
		/*if(enableRCP.recipeEnabled("Pillager"))SpawnerRC.MobRecipes("pillagerKey", EntityType.PILLAGER, "Pillager", CompMaterial.EMERALD.getMaterial(), CompMaterial.BOW.getMaterial(), CompMaterial.EMERALD.getMaterial(), CompMaterial.EMERALD.getMaterial(), CompMaterial.BOW.getMaterial());
		if(enableRCP.recipeEnabled("Ravenger"))SpawnerRC.MobRecipes("ravengerKey", EntityType.RAVENGER, "Ravenger", CompMaterial.SADDLE, CompMaterial.SADDLE, CompMaterial.SADDLE, CompMaterial.SADDLE, CompMaterial.SADDLE);
		if(enableRCP.recipeEnabled("Fox"))SpawnerRC.MobRecipes("foxKey", EntityType.FOX, "Fox", CompMaterial.EMERALD.getMaterial(), CompMaterial.RABBIT_FOOT, CompMaterial., CompMaterial., CompMaterial.);
		if(enableRCP.recipeEnabled("Cat"))SpawnerRC.MobRecipes("catKey", EntityType.CAT, "Cat", CompMaterial., CompMaterial., CompMaterial., CompMaterial., CompMaterial.);
		if(enableRCP.recipeEnabled("Panda"))SpawnerRC.MobRecipes("pandaKey", EntityType.PANDA, "Panda", CompMaterial., CompMaterial., CompMaterial., CompMaterial., CompMaterial.);
		*/
	}
}
