Main Command Enabled: true
Advanced Crafting: true
Enable Cow Recipe: true
Enable Pig Recipe: true
Enable Sheep Recipe: true
Enable Chicken Recipe: true
Enable Rabbit Recipe: true
Enable Squid Recipe: true
Enable Mooshroom Recipe: true
Enable Donkey Recipe: true
Enable Horse Recipe: true
Enable Dolphin Recipe: true
Enable Ocelot Recipe: true
Enable Wolf Recipe: true
Enable Villager Recipe: true
Enable Cave Spider Recipe: true
Enable Enderman Recipe: true
Enable Spider Recipe: true
Enable Zombie Recipe: true
Enable Zombie Pigman Recipe: true
Enable Zombie Villager Recipe: true
Enable Blaze Recipe: true
Enable Creeper Recipe: true
Enable Elder Guardian Recipe: true
Enable Guardian Recipe: true
Enable Ghast Recipe: true
Enable Magma Cube Recipe: true
Enable Silverfish Recipe: true
