Main Command Enabled: true
Advanced Crafting: true
Enable Cow Recipe: true
Enable Pig Recipe: true
Enable Sheep Recipe: true
Enable Chicken Recipe: true
Enable Mooshroom Recipe: true
Enable Dolphin Recipe: true